#!/bin/bash
WALLPAPER_DIR="$HOME/walls"
#I dont know what the fuck I am doing
menu() {
    find "${WALLPAPER_DIR}" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.gif" \) | awk '{print "img:"$0}'
}
main() {
    choice=$(menu | wofi -c ~/.config/wofi/wallpaper -s ~/.config/wofi/style-wallpaper.css --show dmenu --prompt "Select Wallpaper:" -n)
    swww img "$selected_wallpaper" --transition-step 255 --transition-fps 255 --transition-type random
    wal -i "$selected_wallpaper" -n -q
    swaync-client --reload-css
    pywalfox update
    pkill waybar
    waybar &
}
main